# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/GitHub/Basys3/Resources/XDC/Basys3_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_regfile_0_0/design_1_regfile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_regfile_0_0 || ORIG_REF_NAME==design_1_regfile_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IMem_0_0/design_1_IMem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_IMem_0_0 || ORIG_REF_NAME==design_1_IMem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pc_0_0/design_1_pc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pc_0_0 || ORIG_REF_NAME==design_1_pc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_inst_decode_0_0/design_1_inst_decode_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_inst_decode_0_0 || ORIG_REF_NAME==design_1_inst_decode_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_br_ctrl_0_0/design_1_br_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_br_ctrl_0_0 || ORIG_REF_NAME==design_1_br_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_alu_0_0/design_1_alu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_alu_0_0 || ORIG_REF_NAME==design_1_alu_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_control_unit_0_0/design_1_control_unit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_control_unit_0_0 || ORIG_REF_NAME==design_1_control_unit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux2_0_0/design_1_mux2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux2_0_0 || ORIG_REF_NAME==design_1_mux2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux2_1_0/design_1_mux2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux2_1_0 || ORIG_REF_NAME==design_1_mux2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux2_2_0/design_1_mux2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux2_2_0 || ORIG_REF_NAME==design_1_mux2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux2_3_0/design_1_mux2_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux2_3_0 || ORIG_REF_NAME==design_1_mux2_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux2_4_0/design_1_mux2_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux2_4_0 || ORIG_REF_NAME==design_1_mux2_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DMem_0_0/design_1_DMem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DMem_0_0 || ORIG_REF_NAME==design_1_DMem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dataext_0_0/design_1_dataext_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dataext_0_0 || ORIG_REF_NAME==design_1_dataext_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_const_add4_0_0/design_1_const_add4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_const_add4_0_0 || ORIG_REF_NAME==design_1_const_add4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_immext_0_0/design_1_immext_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_immext_0_0 || ORIG_REF_NAME==design_1_immext_0_0} -quiet] -quiet

# XDC: e:/GitHub/EL6463-Team-Project/team_project_rv32i/team_project_rv32i.gen/sources_1/bd/design_1/design_1_ooc.xdc
